// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playlists.proto

package ch.swissproductions.canora.data;

public final class PlaylistsProtoBuff {
  private PlaylistsProtoBuff() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlaylistItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlaylistItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string path = 1;</code>
     */
    boolean hasPath();
    /**
     * <code>required string path = 1;</code>
     */
    String getPath();
    /**
     * <code>required string path = 1;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();
  }
  /**
   * Protobuf type {@code PlaylistItem}
   */
  public  static final class PlaylistItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlaylistItem)
      PlaylistItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlaylistItem.newBuilder() to construct.
    private PlaylistItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlaylistItem() {
      path_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlaylistItem();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlaylistItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              path_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlaylistsProtoBuff.internal_static_PlaylistItem_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlaylistsProtoBuff.internal_static_PlaylistItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PlaylistItem.class, Builder.class);
    }

    private int bitField0_;
    public static final int PATH_FIELD_NUMBER = 1;
    private volatile Object path_;
    /**
     * <code>required string path = 1;</code>
     */
    public boolean hasPath() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string path = 1;</code>
     */
    public String getPath() {
      Object ref = path_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          path_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string path = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, path_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, path_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PlaylistItem)) {
        return super.equals(obj);
      }
      PlaylistItem other = (PlaylistItem) obj;

      if (hasPath() != other.hasPath()) return false;
      if (hasPath()) {
        if (!getPath()
            .equals(other.getPath())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPath()) {
        hash = (37 * hash) + PATH_FIELD_NUMBER;
        hash = (53 * hash) + getPath().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PlaylistItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlaylistItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlaylistItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlaylistItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlaylistItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlaylistItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlaylistItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlaylistItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlaylistItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PlaylistItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlaylistItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlaylistItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PlaylistItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlaylistItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlaylistItem)
        PlaylistItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PlaylistsProtoBuff.internal_static_PlaylistItem_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PlaylistsProtoBuff.internal_static_PlaylistItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PlaylistItem.class, Builder.class);
      }

      // Construct using ch.swissproductions.canora.data.PlaylistsProtoBuff.PlaylistItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PlaylistsProtoBuff.internal_static_PlaylistItem_descriptor;
      }

      @Override
      public PlaylistItem getDefaultInstanceForType() {
        return PlaylistItem.getDefaultInstance();
      }

      @Override
      public PlaylistItem build() {
        PlaylistItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PlaylistItem buildPartial() {
        PlaylistItem result = new PlaylistItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.path_ = path_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PlaylistItem) {
          return mergeFrom((PlaylistItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PlaylistItem other) {
        if (other == PlaylistItem.getDefaultInstance()) return this;
        if (other.hasPath()) {
          bitField0_ |= 0x00000001;
          path_ = other.path_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasPath()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PlaylistItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PlaylistItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object path_ = "";
      /**
       * <code>required string path = 1;</code>
       */
      public boolean hasPath() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string path = 1;</code>
       */
      public String getPath() {
        Object ref = path_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            path_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string path = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string path = 1;</code>
       */
      public Builder setPath(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string path = 1;</code>
       */
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000001);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>required string path = 1;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        path_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlaylistItem)
    }

    // @@protoc_insertion_point(class_scope:PlaylistItem)
    private static final PlaylistItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PlaylistItem();
    }

    public static PlaylistItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<PlaylistItem>
        PARSER = new com.google.protobuf.AbstractParser<PlaylistItem>() {
      @Override
      public PlaylistItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlaylistItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlaylistItem> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PlaylistItem> getParserForType() {
      return PARSER;
    }

    @Override
    public PlaylistItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlaylistOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Playlist)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .PlaylistItem song = 2;</code>
     */
    java.util.List<PlaylistItem>
        getSongList();
    /**
     * <code>repeated .PlaylistItem song = 2;</code>
     */
    PlaylistItem getSong(int index);
    /**
     * <code>repeated .PlaylistItem song = 2;</code>
     */
    int getSongCount();
    /**
     * <code>repeated .PlaylistItem song = 2;</code>
     */
    java.util.List<? extends PlaylistItemOrBuilder>
        getSongOrBuilderList();
    /**
     * <code>repeated .PlaylistItem song = 2;</code>
     */
    PlaylistItemOrBuilder getSongOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code Playlist}
   */
  public  static final class Playlist extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Playlist)
      PlaylistOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Playlist.newBuilder() to construct.
    private Playlist(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Playlist() {
      name_ = "";
      song_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Playlist();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Playlist(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                song_ = new java.util.ArrayList<PlaylistItem>();
                mutable_bitField0_ |= 0x00000002;
              }
              song_.add(
                  input.readMessage(PlaylistItem.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          song_ = java.util.Collections.unmodifiableList(song_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlaylistsProtoBuff.internal_static_Playlist_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlaylistsProtoBuff.internal_static_Playlist_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Playlist.class, Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SONG_FIELD_NUMBER = 2;
    private java.util.List<PlaylistItem> song_;
    /**
     * <code>repeated .PlaylistItem song = 2;</code>
     */
    public java.util.List<PlaylistItem> getSongList() {
      return song_;
    }
    /**
     * <code>repeated .PlaylistItem song = 2;</code>
     */
    public java.util.List<? extends PlaylistItemOrBuilder>
        getSongOrBuilderList() {
      return song_;
    }
    /**
     * <code>repeated .PlaylistItem song = 2;</code>
     */
    public int getSongCount() {
      return song_.size();
    }
    /**
     * <code>repeated .PlaylistItem song = 2;</code>
     */
    public PlaylistItem getSong(int index) {
      return song_.get(index);
    }
    /**
     * <code>repeated .PlaylistItem song = 2;</code>
     */
    public PlaylistItemOrBuilder getSongOrBuilder(
        int index) {
      return song_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSongCount(); i++) {
        if (!getSong(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      for (int i = 0; i < song_.size(); i++) {
        output.writeMessage(2, song_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      for (int i = 0; i < song_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, song_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Playlist)) {
        return super.equals(obj);
      }
      Playlist other = (Playlist) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (!getSongList()
          .equals(other.getSongList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (getSongCount() > 0) {
        hash = (37 * hash) + SONG_FIELD_NUMBER;
        hash = (53 * hash) + getSongList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Playlist parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Playlist parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Playlist parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Playlist parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Playlist parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Playlist parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Playlist parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Playlist parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Playlist parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Playlist parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Playlist parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Playlist parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Playlist prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Playlist}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Playlist)
        PlaylistOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PlaylistsProtoBuff.internal_static_Playlist_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PlaylistsProtoBuff.internal_static_Playlist_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Playlist.class, Builder.class);
      }

      // Construct using ch.swissproductions.canora.data.PlaylistsProtoBuff.Playlist.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSongFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (songBuilder_ == null) {
          song_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          songBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PlaylistsProtoBuff.internal_static_Playlist_descriptor;
      }

      @Override
      public Playlist getDefaultInstanceForType() {
        return Playlist.getDefaultInstance();
      }

      @Override
      public Playlist build() {
        Playlist result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Playlist buildPartial() {
        Playlist result = new Playlist(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (songBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            song_ = java.util.Collections.unmodifiableList(song_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.song_ = song_;
        } else {
          result.song_ = songBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Playlist) {
          return mergeFrom((Playlist)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Playlist other) {
        if (other == Playlist.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (songBuilder_ == null) {
          if (!other.song_.isEmpty()) {
            if (song_.isEmpty()) {
              song_ = other.song_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSongIsMutable();
              song_.addAll(other.song_);
            }
            onChanged();
          }
        } else {
          if (!other.song_.isEmpty()) {
            if (songBuilder_.isEmpty()) {
              songBuilder_.dispose();
              songBuilder_ = null;
              song_ = other.song_;
              bitField0_ = (bitField0_ & ~0x00000002);
              songBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSongFieldBuilder() : null;
            } else {
              songBuilder_.addAllMessages(other.song_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        for (int i = 0; i < getSongCount(); i++) {
          if (!getSong(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Playlist parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Playlist) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<PlaylistItem> song_ =
        java.util.Collections.emptyList();
      private void ensureSongIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          song_ = new java.util.ArrayList<PlaylistItem>(song_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PlaylistItem, PlaylistItem.Builder, PlaylistItemOrBuilder> songBuilder_;

      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public java.util.List<PlaylistItem> getSongList() {
        if (songBuilder_ == null) {
          return java.util.Collections.unmodifiableList(song_);
        } else {
          return songBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public int getSongCount() {
        if (songBuilder_ == null) {
          return song_.size();
        } else {
          return songBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public PlaylistItem getSong(int index) {
        if (songBuilder_ == null) {
          return song_.get(index);
        } else {
          return songBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public Builder setSong(
          int index, PlaylistItem value) {
        if (songBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSongIsMutable();
          song_.set(index, value);
          onChanged();
        } else {
          songBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public Builder setSong(
          int index, PlaylistItem.Builder builderForValue) {
        if (songBuilder_ == null) {
          ensureSongIsMutable();
          song_.set(index, builderForValue.build());
          onChanged();
        } else {
          songBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public Builder addSong(PlaylistItem value) {
        if (songBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSongIsMutable();
          song_.add(value);
          onChanged();
        } else {
          songBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public Builder addSong(
          int index, PlaylistItem value) {
        if (songBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSongIsMutable();
          song_.add(index, value);
          onChanged();
        } else {
          songBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public Builder addSong(
          PlaylistItem.Builder builderForValue) {
        if (songBuilder_ == null) {
          ensureSongIsMutable();
          song_.add(builderForValue.build());
          onChanged();
        } else {
          songBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public Builder addSong(
          int index, PlaylistItem.Builder builderForValue) {
        if (songBuilder_ == null) {
          ensureSongIsMutable();
          song_.add(index, builderForValue.build());
          onChanged();
        } else {
          songBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public Builder addAllSong(
          Iterable<? extends PlaylistItem> values) {
        if (songBuilder_ == null) {
          ensureSongIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, song_);
          onChanged();
        } else {
          songBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public Builder clearSong() {
        if (songBuilder_ == null) {
          song_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          songBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public Builder removeSong(int index) {
        if (songBuilder_ == null) {
          ensureSongIsMutable();
          song_.remove(index);
          onChanged();
        } else {
          songBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public PlaylistItem.Builder getSongBuilder(
          int index) {
        return getSongFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public PlaylistItemOrBuilder getSongOrBuilder(
          int index) {
        if (songBuilder_ == null) {
          return song_.get(index);  } else {
          return songBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public java.util.List<? extends PlaylistItemOrBuilder>
           getSongOrBuilderList() {
        if (songBuilder_ != null) {
          return songBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(song_);
        }
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public PlaylistItem.Builder addSongBuilder() {
        return getSongFieldBuilder().addBuilder(
            PlaylistItem.getDefaultInstance());
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public PlaylistItem.Builder addSongBuilder(
          int index) {
        return getSongFieldBuilder().addBuilder(
            index, PlaylistItem.getDefaultInstance());
      }
      /**
       * <code>repeated .PlaylistItem song = 2;</code>
       */
      public java.util.List<PlaylistItem.Builder>
           getSongBuilderList() {
        return getSongFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PlaylistItem, PlaylistItem.Builder, PlaylistItemOrBuilder>
          getSongFieldBuilder() {
        if (songBuilder_ == null) {
          songBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PlaylistItem, PlaylistItem.Builder, PlaylistItemOrBuilder>(
                  song_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          song_ = null;
        }
        return songBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Playlist)
    }

    // @@protoc_insertion_point(class_scope:Playlist)
    private static final Playlist DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Playlist();
    }

    public static Playlist getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Playlist>
        PARSER = new com.google.protobuf.AbstractParser<Playlist>() {
      @Override
      public Playlist parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Playlist(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Playlist> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Playlist> getParserForType() {
      return PARSER;
    }

    @Override
    public Playlist getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlaylistsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Playlists)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Playlist playlists = 1;</code>
     */
    java.util.List<Playlist>
        getPlaylistsList();
    /**
     * <code>repeated .Playlist playlists = 1;</code>
     */
    Playlist getPlaylists(int index);
    /**
     * <code>repeated .Playlist playlists = 1;</code>
     */
    int getPlaylistsCount();
    /**
     * <code>repeated .Playlist playlists = 1;</code>
     */
    java.util.List<? extends PlaylistOrBuilder>
        getPlaylistsOrBuilderList();
    /**
     * <code>repeated .Playlist playlists = 1;</code>
     */
    PlaylistOrBuilder getPlaylistsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code Playlists}
   */
  public  static final class Playlists extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Playlists)
      PlaylistsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Playlists.newBuilder() to construct.
    private Playlists(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Playlists() {
      playlists_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Playlists();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Playlists(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                playlists_ = new java.util.ArrayList<Playlist>();
                mutable_bitField0_ |= 0x00000001;
              }
              playlists_.add(
                  input.readMessage(Playlist.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          playlists_ = java.util.Collections.unmodifiableList(playlists_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlaylistsProtoBuff.internal_static_Playlists_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlaylistsProtoBuff.internal_static_Playlists_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Playlists.class, Builder.class);
    }

    public static final int PLAYLISTS_FIELD_NUMBER = 1;
    private java.util.List<Playlist> playlists_;
    /**
     * <code>repeated .Playlist playlists = 1;</code>
     */
    public java.util.List<Playlist> getPlaylistsList() {
      return playlists_;
    }
    /**
     * <code>repeated .Playlist playlists = 1;</code>
     */
    public java.util.List<? extends PlaylistOrBuilder>
        getPlaylistsOrBuilderList() {
      return playlists_;
    }
    /**
     * <code>repeated .Playlist playlists = 1;</code>
     */
    public int getPlaylistsCount() {
      return playlists_.size();
    }
    /**
     * <code>repeated .Playlist playlists = 1;</code>
     */
    public Playlist getPlaylists(int index) {
      return playlists_.get(index);
    }
    /**
     * <code>repeated .Playlist playlists = 1;</code>
     */
    public PlaylistOrBuilder getPlaylistsOrBuilder(
        int index) {
      return playlists_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPlaylistsCount(); i++) {
        if (!getPlaylists(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < playlists_.size(); i++) {
        output.writeMessage(1, playlists_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < playlists_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, playlists_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Playlists)) {
        return super.equals(obj);
      }
      Playlists other = (Playlists) obj;

      if (!getPlaylistsList()
          .equals(other.getPlaylistsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPlaylistsCount() > 0) {
        hash = (37 * hash) + PLAYLISTS_FIELD_NUMBER;
        hash = (53 * hash) + getPlaylistsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Playlists parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Playlists parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Playlists parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Playlists parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Playlists parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Playlists parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Playlists parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Playlists parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Playlists parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Playlists parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Playlists parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Playlists parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Playlists prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Playlists}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Playlists)
        PlaylistsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PlaylistsProtoBuff.internal_static_Playlists_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PlaylistsProtoBuff.internal_static_Playlists_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Playlists.class, Builder.class);
      }

      // Construct using ch.swissproductions.canora.data.PlaylistsProtoBuff.Playlists.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPlaylistsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (playlistsBuilder_ == null) {
          playlists_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          playlistsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PlaylistsProtoBuff.internal_static_Playlists_descriptor;
      }

      @Override
      public Playlists getDefaultInstanceForType() {
        return Playlists.getDefaultInstance();
      }

      @Override
      public Playlists build() {
        Playlists result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Playlists buildPartial() {
        Playlists result = new Playlists(this);
        int from_bitField0_ = bitField0_;
        if (playlistsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            playlists_ = java.util.Collections.unmodifiableList(playlists_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.playlists_ = playlists_;
        } else {
          result.playlists_ = playlistsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Playlists) {
          return mergeFrom((Playlists)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Playlists other) {
        if (other == Playlists.getDefaultInstance()) return this;
        if (playlistsBuilder_ == null) {
          if (!other.playlists_.isEmpty()) {
            if (playlists_.isEmpty()) {
              playlists_ = other.playlists_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePlaylistsIsMutable();
              playlists_.addAll(other.playlists_);
            }
            onChanged();
          }
        } else {
          if (!other.playlists_.isEmpty()) {
            if (playlistsBuilder_.isEmpty()) {
              playlistsBuilder_.dispose();
              playlistsBuilder_ = null;
              playlists_ = other.playlists_;
              bitField0_ = (bitField0_ & ~0x00000001);
              playlistsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPlaylistsFieldBuilder() : null;
            } else {
              playlistsBuilder_.addAllMessages(other.playlists_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        for (int i = 0; i < getPlaylistsCount(); i++) {
          if (!getPlaylists(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Playlists parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Playlists) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Playlist> playlists_ =
        java.util.Collections.emptyList();
      private void ensurePlaylistsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          playlists_ = new java.util.ArrayList<Playlist>(playlists_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Playlist, Playlist.Builder, PlaylistOrBuilder> playlistsBuilder_;

      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public java.util.List<Playlist> getPlaylistsList() {
        if (playlistsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(playlists_);
        } else {
          return playlistsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public int getPlaylistsCount() {
        if (playlistsBuilder_ == null) {
          return playlists_.size();
        } else {
          return playlistsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public Playlist getPlaylists(int index) {
        if (playlistsBuilder_ == null) {
          return playlists_.get(index);
        } else {
          return playlistsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public Builder setPlaylists(
          int index, Playlist value) {
        if (playlistsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlaylistsIsMutable();
          playlists_.set(index, value);
          onChanged();
        } else {
          playlistsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public Builder setPlaylists(
          int index, Playlist.Builder builderForValue) {
        if (playlistsBuilder_ == null) {
          ensurePlaylistsIsMutable();
          playlists_.set(index, builderForValue.build());
          onChanged();
        } else {
          playlistsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public Builder addPlaylists(Playlist value) {
        if (playlistsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlaylistsIsMutable();
          playlists_.add(value);
          onChanged();
        } else {
          playlistsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public Builder addPlaylists(
          int index, Playlist value) {
        if (playlistsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlaylistsIsMutable();
          playlists_.add(index, value);
          onChanged();
        } else {
          playlistsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public Builder addPlaylists(
          Playlist.Builder builderForValue) {
        if (playlistsBuilder_ == null) {
          ensurePlaylistsIsMutable();
          playlists_.add(builderForValue.build());
          onChanged();
        } else {
          playlistsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public Builder addPlaylists(
          int index, Playlist.Builder builderForValue) {
        if (playlistsBuilder_ == null) {
          ensurePlaylistsIsMutable();
          playlists_.add(index, builderForValue.build());
          onChanged();
        } else {
          playlistsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public Builder addAllPlaylists(
          Iterable<? extends Playlist> values) {
        if (playlistsBuilder_ == null) {
          ensurePlaylistsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, playlists_);
          onChanged();
        } else {
          playlistsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public Builder clearPlaylists() {
        if (playlistsBuilder_ == null) {
          playlists_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          playlistsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public Builder removePlaylists(int index) {
        if (playlistsBuilder_ == null) {
          ensurePlaylistsIsMutable();
          playlists_.remove(index);
          onChanged();
        } else {
          playlistsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public Playlist.Builder getPlaylistsBuilder(
          int index) {
        return getPlaylistsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public PlaylistOrBuilder getPlaylistsOrBuilder(
          int index) {
        if (playlistsBuilder_ == null) {
          return playlists_.get(index);  } else {
          return playlistsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public java.util.List<? extends PlaylistOrBuilder>
           getPlaylistsOrBuilderList() {
        if (playlistsBuilder_ != null) {
          return playlistsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(playlists_);
        }
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public Playlist.Builder addPlaylistsBuilder() {
        return getPlaylistsFieldBuilder().addBuilder(
            Playlist.getDefaultInstance());
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public Playlist.Builder addPlaylistsBuilder(
          int index) {
        return getPlaylistsFieldBuilder().addBuilder(
            index, Playlist.getDefaultInstance());
      }
      /**
       * <code>repeated .Playlist playlists = 1;</code>
       */
      public java.util.List<Playlist.Builder>
           getPlaylistsBuilderList() {
        return getPlaylistsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Playlist, Playlist.Builder, PlaylistOrBuilder>
          getPlaylistsFieldBuilder() {
        if (playlistsBuilder_ == null) {
          playlistsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Playlist, Playlist.Builder, PlaylistOrBuilder>(
                  playlists_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          playlists_ = null;
        }
        return playlistsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Playlists)
    }

    // @@protoc_insertion_point(class_scope:Playlists)
    private static final Playlists DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Playlists();
    }

    public static Playlists getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Playlists>
        PARSER = new com.google.protobuf.AbstractParser<Playlists>() {
      @Override
      public Playlists parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Playlists(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Playlists> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Playlists> getParserForType() {
      return PARSER;
    }

    @Override
    public Playlists getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlaylistItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlaylistItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Playlist_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Playlist_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Playlists_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Playlists_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017playlists.proto\"\034\n\014PlaylistItem\022\014\n\004pat" +
      "h\030\001 \002(\t\"5\n\010Playlist\022\014\n\004name\030\001 \002(\t\022\033\n\004son" +
      "g\030\002 \003(\0132\r.PlaylistItem\")\n\tPlaylists\022\034\n\tp" +
      "laylists\030\001 \003(\0132\t.PlaylistB5\n\037ch.swisspro" +
      "ductions.canora.dataB\022PlaylistsProtoBuff"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PlaylistItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlaylistItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlaylistItem_descriptor,
        new String[] { "Path", });
    internal_static_Playlist_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Playlist_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Playlist_descriptor,
        new String[] { "Name", "Song", });
    internal_static_Playlists_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Playlists_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Playlists_descriptor,
        new String[] { "Playlists", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
